title: Seminario Visualización de Datos
subtitle: Doctorado en Sociología, Instituto de Altos Estudios Sociales, UNSAM
description: Materiales del curso       
show_downloads: true
theme: jekyll-theme-cayman
